### ISSUE TITLE
Documentation is not beginner friendly

### ISSUE THREAD

**Issue by Kimerrio** [joelbutcher/socialstream-docs#5]
**The doc does not explicitly state the following:**

1. It does not tell that whether you need to install **Laravel socialite** or the package will do it for you.  I recommend you give either examples or scenarios where you would need to installed Laravel socialite, because I've see discussion where it was recommended to be installed.
3. It does not explicitly state the use case scenario. Eg. What are the problems it solving vs existing solutions
4. If Socialstream will handle the business logic such as creating users, etc. I found this out after searching the discussions board
5. If Socialstream will handle the routes for you and you have the ability to publish theses routes.
6.  IF you need to follow Socialstream route schematics when configuring your provider's redirect URI. eg. Google redirect URI
7. It does not give you a setup up work flow after installation.
8. For filament,  if it implement social login on filament panels login
9. Overall the doc is not beginner friendly and assumes you have worked with socialite and social providers in the past.

I recommend a documentation update, the package is great but it takes too long for a beginner like myself to read through discussion board to find out information that should be in the documentation. Please see how quickly this can be updated. I am happy to assist so if you could quickly answer some of the concerns I will can know which directions to go.

Thank you

**Comment by joelbutcher** [comment]
Hey @Kimerrio sorry you've experienced this. I've just published an updated version of the documentation, hopefully that is to a better standard and explains all the things that were missing. Please let me know if you think it can be improved further!

Thanks!
